window.project = true;

// Project Shader Store


// Browser Window Services
var fmodjs,script2;window.firelightAudio=0;window.firelightDebug=!1;(window.firelightAudio===1||window.firelightAudio===2)&&(fmodjs="scripts/fmodstudio.js",fmodjs=window.firelightDebug===!0?"scripts/"+(window.firelightAudio===1)?"fmodstudioL.js":"fmodL.js":"scripts/"+(window.firelightAudio===1)?"fmodstudio.js":"fmod.js",script2=document.createElement("script"),script2.setAttribute("type","text/javascript"),script2.setAttribute("src",fmodjs),document.head!=null?document.head.appendChild(script2):document.body!=null&&document.body.appendChild(script2));window.preferredLaunchMode=0;typeof Windows!="undefined"&&typeof Windows.UI!="undefined"&&typeof Windows.UI.ViewManagement!="undefined"&&typeof Windows.UI.ViewManagement.ApplicationView!="undefined"&&(Windows.UI.ViewManagement.ApplicationView.preferredLaunchWindowingMode=window.preferredLaunchMode===1?Windows.UI.ViewManagement.ApplicationViewWindowingMode.fullScreen:Windows.UI.ViewManagement.ApplicationViewWindowingMode.auto);document.querySelector("style").textContent+="@media (max-height: 1080px) { @-ms-viewport { height: 1080px; } }";window.xboxLiveServices=!1;window.isXboxLivePluginEnabled=function(){var n=typeof Windows!="undefined"&&typeof Microsoft!="undefined"&&typeof Microsoft.Xbox!="undefined"&&typeof Microsoft.Xbox.Services!="undefined",t=typeof BabylonToolkit!="undefined"&&typeof BabylonToolkit.XboxLive!="undefined"&&typeof BabylonToolkit.XboxLive.Plugin!="undefined";return window.xboxLiveServices===!0&&n===!0&&t===!0};window.createGenericPromise=function(n){return new Promise(n)};window.resolveGenericPromise=function(n){return Promise.resolve(n)}

// endeavorbabylon.ts
var PROJECT;(function(n){class t extends BABYLON.MeshComponent{constructor(n,t,i=true,r={}){super(n,t,i,r)}ready(){}start(){}update(){}after(){}destroy(){}}n.NewMeshComponent=t})(PROJECT||(PROJECT={})),function(n){class t extends BABYLON.UniversalShaderMaterial{constructor(n,t,i=true){super(n,t,i);this.program="default";this.setFloat("time",0)}ready(){}start(){this.setFloat("time",0)}update(){this.setFloat("time",this.getManager().time)}define(n){n.defineBoolean("TIME")}after(){}destroy(){}clone(t){var i=BABYLON.SerializationHelper.Clone(()=>new n.WaterMaterialController(t,this.getScene()),this);return BABYLON.UniversalShaderMaterial.CloneCustomProperties(this,i),i}serialize(){var n=BABYLON.SerializationHelper.Serialize(this);return n.customType="PROJECT.WaterMaterialController",BABYLON.UniversalShaderMaterial.SerializeCustomProperties(this,n),n}static Parse(t,i,r){var u=BABYLON.SerializationHelper.Parse(()=>new n.WaterMaterialController(t.name,i),t,i,r);return BABYLON.UniversalShaderMaterial.ParseCustomProperties(u,t,i,r),u}}n.WaterMaterialController=t}(PROJECT||(PROJECT={})),function(n){class t extends BABYLON.MeshComponent{constructor(n,t,i=true,r={}){super(n,t,i,r)}ready(){}start(){let n=this.getProperty("hello","Hello World");console.log("scene Controller says: "+n)}update(){}after(){}destroy(){}}n.SceneController=t}(PROJECT||(PROJECT={})),function(n){class t extends BABYLON.CameraComponent{constructor(n,t,i=true,r={}){super(n,t,i,r)}ready(){}start(){}update(){}after(){}destroy(){}}n.VRCamera=t}(PROJECT||(PROJECT={}))

